{* These settings are included in project source code; change especially the latter parts when the code becomes production ready *}
{.$DEFINE DEBUG} //Leave this to Lazarus or FPC (-dDEBUG). Use DEBUG if you want to dump debug output to stdout.
{.$DEFINE CRAZYDEBUG} //Leave this to Lazarus or FPC (-dCRAZYDEBUG). Use this if you want to dump everything that once was suspect or uncertain.
{$H+}//treat strings as variable length strings unless explicitly specified

{$HINTS ON} //especially for debugging

